#!/usr/bin/env python3
"""
MeeTify Utility Script
Lists all models available for a given Modelslab API key
with detailed features and structured output.

Author: Aditya (Generated by ChatGPT)
"""

import requests
import json
import sys
from typing import Dict, Any, List


# =========================
# CONFIGURATION
# =========================

API_KEY = "wQrSd1q6vvHXovWpiLALJlrZFJvcJzN4iUVex283wYgiOcGHh0CB6DurTwq6"   # <-- Replace with actual key
BASE_URL = "https://modelslab.com/api"


# =========================
# API CALLS
# =========================

def fetch_models() -> Dict[str, Any]:
    """
    Attempts to fetch all models available for the API key.
    Tries multiple possible endpoints.
    """
    endpoints = [
        f"{BASE_URL}/v4/dreambooth/model_list",
        f"{BASE_URL}/v6/llm/model-list"
    ]

    for endpoint in endpoints:
        try:
            print(f"\nTrying endpoint: {endpoint}")
            response = requests.post(endpoint, json={"key": API_KEY}, timeout=30)

            if response.status_code == 200:
                print("✅ Successfully fetched models.")
                return response.json()

            else:
                print(f"⚠️ Endpoint failed with status {response.status_code}")

        except Exception as e:
            print(f"❌ Error calling {endpoint}: {str(e)}")

    raise Exception("Unable to fetch models from Modelslab API.")


# =========================
# MODEL CLASSIFICATION
# =========================

def classify_model(model_data: Dict[str, Any]) -> str:
    """
    Classifies model based on available metadata.
    """
    model_id = model_data.get("model_id", "").lower()

    if any(x in model_id for x in ["llama", "gpt", "chat", "instruct", "mistral"]):
        return "LLM (Chat / Completion)"
    elif any(x in model_id for x in ["flux", "stable", "diffusion", "image"]):
        return "Text-to-Image"
    elif any(x in model_id for x in ["audio", "whisper", "speech"]):
        return "Speech / Audio"
    elif any(x in model_id for x in ["embedding"]):
        return "Embedding Model"
    else:
        return "Other / Unclassified"


# =========================
# DISPLAY FUNCTION
# =========================

def display_models(models: List[Dict[str, Any]]) -> None:
    """
    Pretty prints model information.
    """
    print("\n==============================")
    print("📦 AVAILABLE MODELS")
    print("==============================\n")

    for idx, model in enumerate(models, 1):

        model_id = model.get("model_id", "N/A")
        description = model.get("description", "No description available.")
        category = classify_model(model)
        context_length = model.get("context_length", "Unknown")
        pricing = model.get("pricing", "Not provided")
        capabilities = model.get("capabilities", "Not specified")

        print(f"----------------------------------------")
        print(f"{idx}. Model ID: {model_id}")
        print(f"   Category: {category}")
        print(f"   Context Length: {context_length}")
        print(f"   Description: {description}")
        print(f"   Capabilities: {capabilities}")
        print(f"   Pricing Info: {pricing}")
        print(f"----------------------------------------\n")


# =========================
# SAVE TO FILE
# =========================

def save_to_json(data: Dict[str, Any], filename="modelslab_models_output.json"):
    """
    Saves full API response to a JSON file.
    """
    with open(filename, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4)

    print(f"\n💾 Full model data saved to {filename}")


# =========================
# MAIN EXECUTION
# =========================

def main():
    try:
        data = fetch_models()

        # Depending on API structure
        if isinstance(data, dict) and "models" in data:
            models = data["models"]
        elif isinstance(data, list):
            models = data
        else:
            print("⚠️ Unexpected API structure. Printing raw response:")
            print(json.dumps(data, indent=4))
            save_to_json(data)
            return

        display_models(models)
        save_to_json(data)

    except Exception as e:
        print(f"\n❌ Fatal Error: {str(e)}")
        sys.exit(1)


if __name__ == "__main__":
    main()